### ISSUE TITLE
does'nt work in my FreeCAD 0.19 (14.02.2022 issue)  on my Linux Mint 21 Vanessa

### ISSUE THREAD

**Issue by ClementCLARISSE** [QuentinTournier40/AnimationFreeCAD#13]
hi,

I've got an issue when i want tot try this workshop: it's claim that "nine" is missing but it's in the right folder under the name "nine-1.1.0"

So i tried by renaming it just "nine", it was'nt better.

What shoud i do ?

Here's what terminal return:

o module named 'nine'
Traceback (most recent call last):
  File "<string>", line 18, in Initialize
  File "/usr/lib/python3/dist-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/clement/.FreeCAD/Mod/AnimationFreeCAD/pyflow_start.py", line 2, in <module>
    from PyFlow.App import PyFlow
  File "/usr/lib/python3/dist-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/clement/.FreeCAD/Mod/AnimationFreeCAD/PyFlow/App.py", line 34, in <module>
    from PyFlow.Core.Common import currentProcessorTime
  File "/usr/lib/python3/dist-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/clement/.FreeCAD/Mod/AnimationFreeCAD/PyFlow/Core/__init__.py", line 21, in <module>
    from PyFlow.Core.PinBase import PinBase
  File "/usr/lib/python3/dist-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/clement/.FreeCAD/Mod/AnimationFreeCAD/PyFlow/Core/PinBase.py", line 21, in <module>
    from nine import str

**Comment by caco3** [comment]
Try to install it globally, it worked for me this way: `sudo python3 -m pip install nine`

Note that i also had to install `docutils`
